import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from 'next/font/google'

const poppins_init = Poppins({
  subsets: ['latin'],
  weight: ['100', '300', '700'],
  variable: '--font-poppins',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${poppins_init.variable} poppins antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
