import localFont from "next/font/local";
import "./globals.css";
import { Poppins } from 'next/font/google'
import Navbar from "@/components/navbar";

const poppins_init = Poppins({
  subsets: ['latin'],
  weight: ['100', '300', '500', '400', '700'],
  variable: '--font-poppins',
})

export const metadata = {
  title: "Create",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${poppins_init.variable} poppins antialiased`}
      >
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
